src/main/java/edu/iit/sat/itmd4515/lmiro/domain/Resturant.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.lmiro.domain;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.validation.constraints.FutureOrPresent;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

/**
 *
 * @author lynnmiro
 */
@Entity
@NamedQuery(name = "Resturant.findAll", query = "select r from Resturant r")
@NamedQuery(name = "Resturant.findByName", query = "select r from Resturant r where r.name = :name")
public class Resturant extends AbstractNamedEntity {

    // inverse side of the relationship
    @OneToMany(mappedBy = "resturant")
    private List<Reservation> reservations = new ArrayList<>();

    // inverse side of the relationship
    @OneToMany(mappedBy = "resturant")
    private List<TableRest> tables = new ArrayList<>();
    @Enumerated(EnumType.STRING)
    private RestType type;
    @NotNull
    @Column(nullable = false)
    private Integer cost;

    /**
     * this Resturant Class constructor
     */
    public Resturant() {
    }

    /**
     *
     * @param name
     * @param type
     * @param cost
     */
    public Resturant(String name, RestType type, Integer cost, LocalDate date) {
        this.name = name;
        this.type = type;
        this.cost = cost;
    }

    /**
     * Get the value of type
     *
     * @return the value of type
     */
    public RestType getType() {
        return type;
    }

    /**
     * set the value of type
     *
     * @param type new value of type
     */
    public void setType(RestType type) {
        this.type = type;
    }

    /**
     * Get the value of cost
     *
     * @return the value of cost
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * set the value of cost
     *
     * @param cost new value of cost
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * Get the value of reservations
     *
     * @return the value of reservations
     */
    public List<Reservation> getReservations() {
        return reservations;
    }

    /**
     * set the value of reservations
     *
     * @param reservations new value of reservations
     */
    public void setReservations(List<Reservation> reservations) {
        this.reservations = reservations;
    }

    /**
     * Get the value of tables
     *
     * @return the value of tables
     */
    public List<TableRest> getTables() {
        return tables;
    }

    /**
     * set the value of tables
     *
     * @param tables new value of tables
     */
    public void setTables(List<TableRest> tables) {
        this.tables = tables;
    }

    @Override
    public String toString() {
        return "Resturant{" + "id=" + id + ", name=" + name + ", type=" + type + ", cost=" + cost + '}';
    }

}

src/main/java/edu/iit/sat/itmd4515/lmiro/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.lmiro.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.security.enterprise.AuthenticationStatus;
import javax.security.enterprise.SecurityContext;
import javax.security.enterprise.authentication.mechanism.http.AuthenticationParameters;
import javax.security.enterprise.credential.Credential;
import javax.security.enterprise.credential.Password;
import javax.security.enterprise.credential.UsernamePasswordCredential;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.constraints.NotBlank;

/**
 *
 * @author lynnmiro
 */
@Named
@RequestScoped
public class LoginController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotBlank(message = "You must enter a username")
    private String username;
    @NotBlank(message = "You must enter a password")
    private String password;

    @Inject
    private SecurityContext securityContext;
    @Inject
    private FacesContext facesContext;

    /**
     * constructor of LoginController class
     */
    public LoginController() {
    }

    /**
     * this method to give the user the appropriate context in the application
     *
     * @return the context of each user
     */
    public String getRemoteUser() {
        return facesContext.getExternalContext().getRemoteUser();
    }

    /**
     * this method is checking the roles of the user if admin or admin rest or
     * customer
     *
     * @return the security context of each user depends on the role
     */
    public String getRoles() {
        return securityContext.toString();
    }

    /**
     * this method is checking if this is a admin restaurant and return true or
     * false
     *
     * @return if the user is in the admin restaurant role by returning true or
     * false
     */
    public boolean isAdminRest() {
        return securityContext.isCallerInRole("ADMINREST_ROLE");
    }

    /**
     * this method is checking if this is a customer and return true or false
     *
     * @return if the user is in the customer role by returning true or false
     */
    public boolean isCustomer() {
        return securityContext.isCallerInRole("CUSTOMER_ROLE");
    }

    /**
     * this method is checking if this is an admin and return true or false
     *
     * @return if the user is in the admin role by returning true or false
     */
    public boolean isAdmin() {
        return securityContext.isCallerInRole("ADMIN_ROLE");
    }

    /**
     * this method is to fire the action of login in the front end. It starts by
     * checking the credentials of the username and password and authenticate
     * credentials if it is success login, the user will continue to welcome
     * page otherwise will go to error page
     *
     * @return redirect the user to the welcome page
     */
    public String doLogin() {
        LOG.info("inside doLogin method");
        Credential credential = new UsernamePasswordCredential(username, new Password(password));

        AuthenticationStatus status = securityContext.authenticate(
                (HttpServletRequest) facesContext.getExternalContext().getRequest(),
                (HttpServletResponse) facesContext.getExternalContext().getResponse(),
                AuthenticationParameters.withParams().credential(credential)
        );

        LOG.info("AuthenticationStatus is: " + status.toString());

        switch (status) {
            case SEND_CONTINUE:
                LOG.info("SEND_CONTINUE in login");
                break;
            case SEND_FAILURE:
                LOG.info("SEND_FAILURE in login");
                return "/error.xhtml";
            case SUCCESS:
                LOG.info("SUCCESS in login");
                break;
            case NOT_DONE:
                LOG.info("NOT_DONE in login");
                return "/error.xhtml";
        }

        return "/welcome.xhtml?faces-redirect=true";
    }

    /**
     * this method to logout the user of the application and if the request of
     * logout did not work then the user will be directed to the error page
     *
     * @return redirect the user to the sign in page
     */
    public String doLogout() {

        try {
            HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
            req.logout();

        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            return "/error.xhtml";
        }

        LOG.info("Logged out and redirecting to login page");
        return "/login.xhtml?faces-redirect=true";

    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * set the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/java/edu/iit/sat/itmd4515/lmiro/web/ResturantController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// mini controllers// backing beans JSF
package edu.iit.sat.itmd4515.lmiro.web;

import edu.iit.sat.itmd4515.lmiro.domain.RestType;
import edu.iit.sat.itmd4515.lmiro.domain.Resturant;
import edu.iit.sat.itmd4515.lmiro.service.ResturantService;
import java.util.List;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author lynnmiro
 */
@Named
@RequestScoped
public class ResturantController {

    private static final Logger LOG = Logger.getLogger(ResturantController.class.getName());

    @EJB
    private ResturantService resturantSvc;

    @Inject
    LoginController loginController;

    private Resturant resturant;

    /**
     * this constructor of ResturantController class
     */
    public ResturantController() {
    }

    @PostConstruct
    private void postConstruct() {
        LOG.info("inside restController.postConstruct()");

        resturant = new Resturant();
    }

    /**
     * this method to fire action in the front end when clicking on View
     * Restaurant
     *
     * @param resturant
     * @return redirect the user to the view Restaurant page of the admin pages
     */
    public String prepareViewResturant(Resturant resturant) {
        LOG.info("Inside prepareViewResturant with Resturant " + resturant.toString());
        this.resturant = resturant;
        return "/admin/viewResturant.xhtml";
    }

    /**
     * this method to fire action in the front end when clicking on Edit
     * Restaurant
     *
     * @param resturant
     * @return redirect the user to the edit Restaurant page of the admin pages
     */
    public String prepareEditResturant(Resturant resturant) {
        LOG.info("Inside prepareResturant with Resturant " + resturant.toString());
        this.resturant = resturant;
        return "/admin/editResturant.xhtml";
    }

    /**
     * this method to fire action in the front end when clicking on delete
     * Restaurant param and it does remove it from the db
     *
     * @param resturant
     * @return redirect the user to the welcome page of admin
     */
    public String doDeleteResturant(Resturant resturant) {
        LOG.info("Inside prepareDeleteResturant with Resturant " + resturant.toString());
        resturantSvc.remove(resturant);
        return "/admin/welcome.xhtml";
    }

    /**
     * this method creates a new restaurant in the db
     *
     * @return redirect the admin to the confirmation page of "restauarantok"
     */
    public String executeSaveRest() {
        LOG.info("inside ResturantController.executeSaveRest()" + resturant.toString());
        resturantSvc.create(resturant);
        return "/admin/resturantok.xhtml";
    }

    /**
     * this method is checking if this restaurant id exists in the db then,
     * update the restaurant information otherwise if there is no restaurant at
     * all, go and create a new restaurant in the db
     *
     * @return redirect the admin to welcome page
     */
    public String doSaveResturant() {
        // when complete, this method will invoke service layer
        // this method will need to be smart enough to know when to edit, and when to create
        LOG.info("Inside doSaveReservation with reservation " + resturant.toString());

        if (this.resturant.getId() != null) {
            LOG.info("Preparing to call an update in the service lyaer with " + this.resturant.toString());
            resturantSvc.editRestNoChangeToAdmin(resturant);
        } else {
            LOG.info("Preparing to create in the service lyaer with " + this.resturant.toString());
            resturantSvc.create(resturant);
        }
        return "/admin/welcome.xhtml?faces-redirect=true";
    }

    /**
     * Get the value of RestType[]
     *
     *
     * @return the value of RestType[]
     */
    public RestType[] getRestTypes() {
        return RestType.values();
    }

    /**
     * Get the list of the restaurants
     *
     *
     * @return all the restaurants that they are stored in the db
     */
    public List<Resturant> getAllRests() {
        return resturantSvc.findAll();
    }

    /**
     * Set the value of restaurant
     *
     * @param resturant new value of restaurant
     */
    public void setResturant(Resturant resturant) {
        this.resturant = resturant;
    }

    /**
     * Get the value of restaurant
     *
     * @return the value of restaurant
     */
    public Resturant getResturant() {
        return resturant;
    }

}

src/main/webapp/admin/editResturant.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Admin Content
    </ui:define>

    <ui:define name="content">
        Welcome Admin #{loginController.remoteUser}

        <ezcomp:resturant resturant="#{resturantController.resturant}" readonly="false" action="#{resturantController.doSaveResturant()}"/>
        <h:link outcome="/admin/welcome.xhtml" value="Return to Home Page"/>
          
               
    </ui:define>
</ui:composition>

src/main/webapp/admin/resturantform.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Restaurant Form
    </ui:define>

    <ui:define name="content">
        <h:form>    
            <h:panelGroup layout="block" class="form-group">
                <h:outputLabel value="Name:" for="restName"/>
                <h:inputText class="form-control" id="restName" value="#{resturantController.resturant.name}"/>
                <h:message for="restName" errorClass="text-danger"/>
            </h:panelGroup>

            <h:panelGroup layout="block" class="form-group">
                <h:outputLabel value="Resturant Type:" for="restType"/>
                <h:selectOneMenu 
                    class="form-control" id="restType" value="#{resturantController.resturant.type}">
                    <f:selectItems value="#{resturantController.restTypes}"
                                   var="type"
                                   itemLabel="#{type.label}"
                                   itemValue="#{type}"/>
                </h:selectOneMenu>
                <h:message for="restType" errorClass="text-danger"/>
            </h:panelGroup>

            <h:panelGroup layout="block" class="form-group">
                <h:outputLabel value="Price $$: " for="restCost"/>

                <h:selectOneMenu class="form-control" id="restCost" value="#{resturantController.resturant.cost}">
                    <f:selectItem itemValue="1"/>
                    <f:selectItem itemValue="2"/>
                    <f:selectItem itemValue="3"/>

                    <f:validateLongRange minimum="1" maximum="5" />
                </h:selectOneMenu>
                <h:message for="restCost" errorClass="text-danger"/>

            </h:panelGroup>
            <h:commandButton value="Submit" class="btn btn-primary" action="#{resturantController.executeSaveRest()}"/>
        </h:form>  
        <h:link outcome="/admin/welcome.xhtml" value="Return to Home Page"/>

    </ui:define>

</ui:composition>

src/main/webapp/admin/resturantok.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="title">
         A New Restaurant Has Been Added 
    </ui:define>

    <ui:define name="content">
        <ul>
            <li>ID : #{resturantController.resturant.id}</li>
            <li>Name : #{resturantController.resturant.name}</li>
<!--            <li>#{resturantController.resturant.type}</li>-->
            <li>Type : #{resturantController.resturant.type.label}</li>
            <li>Cost : #{resturantController.resturant.cost}</li>
        </ul>
        <h:link outcome="/admin/welcome.xhtml" value="Return to Home Page"/>
    </ui:define>

</ui:composition>

src/main/webapp/admin/viewResturant.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Admin Content
    </ui:define>

    <ui:define name="content">
        Welcome Admin #{loginController.remoteUser}

        <ezcomp:resturant resturant="#{resturantController.resturant}" readonly="true"/>
          
        <h:link outcome="/admin/welcome.xhtml" value="Return to Home Page"/>
               
    </ui:define>
</ui:composition>

src/main/webapp/admin/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/portalTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
            Welcome Page - Admin
    </ui:define>

    <ui:define name="content">
        <div style ="color: green">
            Welcome Administrator #{loginController.remoteUser}
        </div>

        <h:form>
            <h:commandButton value="Add New Restaurant" class="btn btn-primary" action="/admin/resturantform.xhtml"/>
        </h:form> 
       <h:dataTable 
            class="table table-striped table-hover"            
            value="#{resturantService.findAll()}" 
            var="resturant">
            <h:column>
                <h:outputText value="#{resturant.id}"></h:outputText>
                <f:facet name="header"><h:outputText value="ID"/></f:facet>
            </h:column>

            <h:column>
                <h:outputText value="#{resturant.name}"></h:outputText>
                <f:facet name="header"><h:outputText value="Name"/></f:facet>
            </h:column>

            <h:column>
                <h:outputText value="#{resturant.cost}"></h:outputText>
                <f:facet name="header"><h:outputText value="Cost Range"/></f:facet>
            </h:column>

            <h:column>
                <h:outputText value="#{resturant.type.label}"></h:outputText>
                <f:facet name="header"><h:outputText value="Resturant Type"/></f:facet>
            </h:column> 
            <h:column>
                <h:form>
                    <h:commandLink action="#{resturantController.prepareViewResturant(resturant)}" value="View "/>
                    <h:commandLink action="#{resturantController.prepareEditResturant(resturant)}" value="Update "/>
                    <h:commandLink action="#{resturantController.doDeleteResturant(resturant)}" value="Delete"/>
                </h:form>
            </h:column>                
        </h:dataTable>        
    </ui:define>
</ui:composition>