src/main/java/edu/iit/sat/itmd4515/lmiro/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.lmiro.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.security.enterprise.AuthenticationStatus;
import javax.security.enterprise.SecurityContext;
import javax.security.enterprise.authentication.mechanism.http.AuthenticationParameters;
import javax.security.enterprise.credential.Credential;
import javax.security.enterprise.credential.Password;
import javax.security.enterprise.credential.UsernamePasswordCredential;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.constraints.NotBlank;

/**
 *
 * @author lynnmiro
 */
@Named
@RequestScoped
public class LoginController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotBlank(message = "You must enter a username")
    private String username;
    @NotBlank(message = "You must enter a password")
    private String password;

    @Inject
    private SecurityContext securityContext;
    @Inject
    private FacesContext facesContext;

    /**
     * constructor of LoginController class
     */
    public LoginController() {
    }

    /**
     * this method to give the user the appropriate context in the application
     *
     * @return the context of each user
     */
    public String getRemoteUser() {
        return facesContext.getExternalContext().getRemoteUser();
    }

    /**
     * this method is checking the roles of the user if admin or admin rest or
     * customer
     *
     * @return the security context of each user depends on the role
     */
    public String getRoles() {
        return securityContext.toString();
    }

    /**
     * this method is checking if this is a admin restaurant and return true or
     * false
     *
     * @return if the user is in the admin restaurant role by returning true or
     * false
     */
    public boolean isAdminRest() {
        return securityContext.isCallerInRole("ADMINREST_ROLE");
    }

    /**
     * this method is checking if this is a customer and return true or false
     *
     * @return if the user is in the customer role by returning true or false
     */
    public boolean isCustomer() {
        return securityContext.isCallerInRole("CUSTOMER_ROLE");
    }

    /**
     * this method is checking if this is an admin and return true or false
     *
     * @return if the user is in the admin role by returning true or false
     */
    public boolean isAdmin() {
        return securityContext.isCallerInRole("ADMIN_ROLE");
    }

    /**
     * this method is to fire the action of login in the front end. It starts by
     * checking the credentials of the username and password and authenticate
     * credentials if it is success login, the user will continue to welcome
     * page otherwise will go to error page
     *
     * @return redirect the user to the welcome page
     */
    public String doLogin() {
        LOG.info("inside doLogin method");
        Credential credential = new UsernamePasswordCredential(username, new Password(password));

        AuthenticationStatus status = securityContext.authenticate(
                (HttpServletRequest) facesContext.getExternalContext().getRequest(),
                (HttpServletResponse) facesContext.getExternalContext().getResponse(),
                AuthenticationParameters.withParams().credential(credential)
        );

        LOG.info("AuthenticationStatus is: " + status.toString());

        switch (status) {
            case SEND_CONTINUE:
                LOG.info("SEND_CONTINUE in login");
                break;
            case SEND_FAILURE:
                LOG.info("SEND_FAILURE in login");
                return "/error.xhtml";
            case SUCCESS:
                LOG.info("SUCCESS in login");
                break;
            case NOT_DONE:
                LOG.info("NOT_DONE in login");
                return "/error.xhtml";
        }

        return "/welcome.xhtml?faces-redirect=true";
    }

    /**
     * this method to logout the user of the application and if the request of
     * logout did not work then the user will be directed to the error page
     *
     * @return redirect the user to the sign in page
     */
    public String doLogout() {

        try {
            HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
            req.logout();

        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            return "/error.xhtml";
        }

        LOG.info("Logged out and redirecting to login page");
        return "/login.xhtml?faces-redirect=true";

    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * set the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/webapp/WEB-INF/templates/portalTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions">

    <h:head>
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <!-- Required meta tags -->
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>

        <!-- Custom styles for this template -->
        <h:outputStylesheet library="css" name="starter-template.css"/>
    </h:head>
    <h:body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>   

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    
                    <li class="#{fn:startsWith(view.viewId, '/welcome') ? 'nav-item active' : 'nav-item'}">
                        <h:link class="nav-link" outcome="/welcome.xhtml" value="Home"/>
                    </li>  
                    
                    <ui:fragment rendered="#{loginController.customer}">                    
                    <li class="#{fn:startsWith(view.viewId, '/customer') ? 'nav-item active' : 'nav-item'}">
                        <h:link class="nav-link" outcome="/customer/welcome.xhtml" value="Customer Portal"/>
                    </li>
                    </ui:fragment>
                        
                    <ui:fragment rendered="#{loginController.adminRest}">                    
                    <li class="#{fn:startsWith(view.viewId, '/adminrest') ? 'nav-item active' : 'nav-item'}">
                        <h:link class="nav-link" outcome="/adminrest/welcome.xhtml" value="Restuarant Administrator Portal"/>
                    </li> 
                    </ui:fragment>
                        
                    <ui:fragment rendered="#{loginController.admin}">                                            
                    <li class="#{fn:startsWith(view.viewId, '/admin') ? 'nav-item active' : 'nav-item'}">
                        <h:link class="nav-link" outcome="/admin/welcome.xhtml" value="Admin Portal"/>                                                
                    </li> 
                    </ui:fragment>
        
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <h:form>
                                <h:commandLink class="dropdown-item" action="#{loginController.doLogout()}" value="Logout"/>                                
                            </h:form>
                        </div>
                    </li>
                </ul>  
                <ul class="navbar-nav mr-sm-2">
                    <li class="#{fn:startsWith(view.viewId, '/profile') ? 'nav-item active' : 'nav-item'}">
                        <h:link class="nav-link" outcome="/profile.xhtml" value="#{loginController.remoteUser}"/>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="starter-template">
                <h1><ui:insert name="title">Default Title</ui:insert></h1>
                <ui:insert name="content">Default Content</ui:insert>
            </div>
        </main><!-- /.container --> 


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </h:body>
</html>

src/main/webapp/WEB-INF/templates/signinTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <!-- Required meta tags -->
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>

        <!-- Custom styles for this template -->
        <h:outputStylesheet library="css" name="signin.css" />
    </h:head>
    <h:body>
        <main role="main" class="container">

            <div class="text-center">

                <ui:insert name="content">Default Content</ui:insert>

            </div>
        </main><!-- /.container -->

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    

    </h:body>
</html>